PASSWORD_SERVER	= 'shoamiphio0o'
PASSWORD_ROOT_CA	= 'PerekatipoleRootJOZEPH'
PASSWORD_SUB_CA	= 'PerekatipoleSubJOZEPH'
PASSWORD_CLIENT	= 'Mistake+'
USER_NAME	= 'arest@arest-home.pp.ua'
ROOT_CA_DEFAULT_DAYS  = '3650'
SUB_CA_DEFAULT_DAYS  = '3650'
